// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMIzFDGEmdcCDPLO6UfOfC_xlMHVVE4T4',
    appId: '1:382628391057:web:98ae7f397e975d680d7730',
    messagingSenderId: '382628391057',
    projectId: 'flutter-test-2baaf',
    authDomain: 'flutter-test-2baaf.firebaseapp.com',
    storageBucket: 'flutter-test-2baaf.firebasestorage.app',
    measurementId: 'G-4VCVRKGNCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD2CLv295y71I25aZUBN4A1mf6QmmAWqE',
    appId: '1:382628391057:android:0c41898dfca614e80d7730',
    messagingSenderId: '382628391057',
    projectId: 'flutter-test-2baaf',
    storageBucket: 'flutter-test-2baaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8WYlcxelBOgSuRLsiH4Uiv_CTr45h50w',
    appId: '1:382628391057:ios:1a72b6cec8a27c690d7730',
    messagingSenderId: '382628391057',
    projectId: 'flutter-test-2baaf',
    storageBucket: 'flutter-test-2baaf.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8WYlcxelBOgSuRLsiH4Uiv_CTr45h50w',
    appId: '1:382628391057:ios:1a72b6cec8a27c690d7730',
    messagingSenderId: '382628391057',
    projectId: 'flutter-test-2baaf',
    storageBucket: 'flutter-test-2baaf.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
